import Providers from "@/components/providers";
import "./globals.css";
import type { Metadata } from "next";
import { bricolageGrotesque } from "@/lib/fonts";
import Background from "@/components/ui/background";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/toast";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={cn(
                    bricolageGrotesque.className,
                    "w-screen overflow-x-hidden",
                )}
            >
                <Providers>
                    {children}
                    <Background />
                    <Toaster />
                </Providers>
            </body>
        </html>
    );
}
