import Providers from "@/components/providers";
import "./globals.css";
import type { Metadata } from "next";
import { bricolageGrotesque } from "@/lib/fonts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={bricolageGrotesque.className}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
